/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.3.0.109 */
/* Module Version: 5.6 */
/* Sun Dec 21 21:19:51 2014 */

/* parameterized module instance */
pll_pix2byte_RGB888_2lane __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), 
    .CLKOS2( ), .LOCK( ));
