/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.3.0.109 */
/* Module Version: 5.6 */
/* Fri Dec 26 18:04:01 2014 */

/* parameterized module instance */
pll_x4 __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
