/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.3.0.109 */
/* Module Version: 5.6 */
/* Sat Dec 27 16:23:57 2014 */

/* parameterized module instance */
pll __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), .LOCK( ));
