/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Wed Feb 16 16:05:57 2022 */

/* parameterized module instance */
pll_pix2byte_RGB888_2lane __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), 
    .CLKOS2( ), .LOCK( ));
