/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.3.0.109 */
/* Module Version: 5.7 */
/* Thu Dec 25 22:49:38 2014 */

/* parameterized module instance */
simulation_fifo_24bit_to_24bit __ (.Data( ), .WrClock( ), .RdClock( ), 
    .WrEn( ), .RdEn( ), .Reset( ), .RPReset( ), .Q( ), .Empty( ), 
    .Full( ), .AlmostEmpty( ), .AlmostFull( ));
