/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Wed Feb 16 16:18:22 2022 */

/* parameterized module instance */
PLL_12_24_100 __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ));
